-- ============================================================
-- werkeins Lager – Startbestand Import
-- Einfügen im Supabase SQL Editor → Run
-- ============================================================

-- 1. LIEFERANTEN
INSERT INTO lieferanten (id, name, email, telefon, bestellweg, webshop_url, kundennummer, lieferzeit, notiz) VALUES
  ('00000000-0000-0000-0000-000000000001', 'DocCheck Shop GmbH',     'info@doccheckshop.at',      '0800 700 272',    'online', 'https://www.doccheckshop.at', '4076909', '2–4 Werktage', null),
  ('00000000-0000-0000-0000-000000000002', 'Ärztebedarf Scherer GmbH','office@scherer.at',         '+43 5578 74750',  'email',  'https://www.scherer.at',      '214447',  '1–2 Werktage', 'Ansprechpartner: Michael Pressnig · Frei Haus ab EUR 200 Netto'),
  ('00000000-0000-0000-0000-000000000003', 'Hofsteig-Apotheke',       'office@hofsteig-apotheke.at','+43 5574 74344', 'email',  null,                          '205346',  '1 Werktag',    '10% Rabatt auf alle Artikel');

-- 2. ARTIKEL
-- (lieferant_id wird per Subquery aufgelöst)

INSERT INTO artikel (bezeichnung, kategorie, lieferant_id, lieferant_artikelnr, einheit, mindestbestand, kritisch, letzter_preis, notiz) VALUES

-- DocCheck
('Dr. No Venenstauer, grün',                        'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102362.4',      'Stück',     2,  false,  2.15,  null),
('Nitril 3000 Handschuhe Gr. S',                    'Handschuhe',         (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '114891',        'P/100',     1,  false,  5.39,  null),
('Nitril 3000 Handschuhe Gr. M',                    'Handschuhe',         (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '115634',        'P/100',     2,  false,  5.39,  null),
('Nitril 3000 Handschuhe Gr. L',                    'Handschuhe',         (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '115635',        'P/100',     1,  false,  5.39,  null),
('Vasco OP Sensitive Latexhandschuhe Gr. 7,5',      'Handschuhe',         (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '125148',        'P/40 Paar', 1,  false, 43.14,  'Puderfreie Latexhandschuhe, steril'),
('Venofix Safety G19 creme 1,10×19mm',              'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102598.4',      'P/50',      1,  false, 35.94,  '30 cm Schlauchlänge'),
('Sterican Einmalkanülen Neuraltherapie G23 0,60×80mm','Kanülen / Spritzen',(SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),  '115202',        'P/100',     1,  false, 14.34,  'Spezial-Facetten-Langschliff, blau'),
('Omnifix Solo 3ml Einmalspritze Luer-Lock',        'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '160361',        'P/100',     1,  false, 23.94,  '3-teilig'),
('Omnifix Solo 5ml Einmalspritze Luer-Lock',        'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '111041',        'P/100',     1,  false, 23.34,  '3-teilig'),
('Omnifix Solo 10ml Einmalspritze Luer-Lock',       'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '115239',        'P/100',     1,  false, 29.34,  '3-teilig'),
('Spritze 20ml Luer-Lock zentrisch',                'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '121366',        'P/50',      1,  false, 25.74,  '3-teilig'),
('DART intranasaler Zerstäuber mit 3ml Spritze',    'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102982.0',      'Stück',     1,  false,  6.59,  null),
('Peha-haft latexfrei Fixierbinde 8cm×21m',         'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102699.0',      'Stück',     2,  false, 14.34,  null),
('Gazofix color Fixierbinde 6cm×20m grün',          'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '175291',        'Stück',     2,  false, 19.14,  null),
('Gazofix color Fixierbinde 8cm×20m grün',          'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '175292',        'Stück',     1,  false, 21.54,  null),
('Hansaplast Fixierpflaster Sensitive 5m×2,5cm',    'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '103417.1',      'Stück',     1,  false,  3.95,  null),
('Schnell-Desinfektionstücher alkoholfrei Spenderdose','Desinfektion',     (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '115578',        'P/100',     2,  false,  9.54,  null),
('Schnell-Desinfektionstücher alkoholfrei Nachfüllpackung','Desinfektion', (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '115579',        'P/100',     1,  false,  8.34,  null),
('Bode X-Wipes Spendereimer leer (Deckel grün)',    'Desinfektion',       (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '156582',        'Stück',     1,  false, 14.34,  null),
('Bode X-Wipes Vliesrolle 90 Tücher',               'Desinfektion',       (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '156579',        'P/90',      1,  false, 11.94,  null),
('Pur-Zellin Spenderbox für Tupfer',                'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '175494',        'Stück',     1,  false, 26.34,  null),
('Pur-Zellin Zellstofftupfer keimreduziert 4×5cm',  'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102869.0',      'Rolle/500', 1,  false,  3.59,  null),
('Entsorgungsbehälter Multi-Safe twin plus 3000ml', 'Sonstiges',          (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '102310.0',      'Stück',     1,  false,  3.47,  'Sharps-Container'),
('Einmalhandtücher grün 25×23cm Recycling V-Falz',  'Sonstiges',          (SELECT id FROM lieferanten WHERE name='DocCheck Shop GmbH'),     '113526',        'P/5000',    1,  false, 35.94,  null),

-- Scherer
('OP-Mundschutz blau 3-lagig Gummiband',            'Sonstiges',          (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'15000429',     'Stück',    50,  false,  0.17,  'PKG = 50 Stk'),
('BD Discardit II Spritze Luer zentrisch 2ml',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'300928',       'Stück',    50,  false,  0.05,  null),
('BD Discardit II Spritze Luer exzentr. 5ml',       'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'309050',       'Stück',    50,  false,  0.06,  null),
('BD Discardit II Spritze Luer exzentr. 10ml',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'309110',       'Stück',    50,  false,  0.08,  null),
('BD Discardit II Spritze Luer exzentr. 20ml',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'300296',       'Stück',    50,  false,  0.12,  null),
('B.Braun Sterican Insulinkanüle 30G 0,30×12mm gelb','Kanülen / Spritzen',(SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'4656300',      'P/100',     1,  false,  4.95,  null),
('B.Braun Sterican Kanüle 27G 0,40×40mm grau',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'9186182',      'P/100',     1,  false,  7.15,  null),
('Neopoint Sonderkanüle Tuberkulin lang 25G 0,50×40mm','Kanülen / Spritzen',(SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'L1 0302',    'P/100',     1,  false,  5.05,  null),
('Neopoint Einmalkanüle 23G 0,60×30mm blau',        'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'L1 0214',      'P/100',     1,  false,  3.50,  null),
('B.Braun Sterican Kanüle 23G 0,60×60mm blau',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'4665600',      'P/100',     1,  false,  7.21,  '23G × 2 3/8'),
('BD Microlance Normkanüle 21G 0,80×40mm grün',     'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'304432',       'P/100',     1,  false,  3.95,  null),
('Neopoint Einmalkanüle 20G 0,90×40mm gelb',        'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'L1 0201',      'P/100',     1,  false,  3.25,  null),
('B.Braun Sterican Einmalkanüle 21G 0,80×80mm grün','Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'4665465',      'P/100',     1,  false, 12.75,  '21G × 3 1/8'),
('BD Blunt Fill Safety Aufziehkanüle 18G 1,2×40mm rot','Kanülen / Spritzen',(SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'303129',     'P/100',     1,  false, 16.95,  null),
('Leukoplast Soft White Injektionspflaster 1,9×4cm','Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'7645026',      'P/500',     1,  false, 29.17,  null),
('Leukoplast Soft White 6cm×5m',                    'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'7645001',      'Stück',     2,  false, 22.29,  null),
('Gazin Mullkompressen 12-fach 5×5cm unsteril',     'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'18501',        'P/100',     1,  false,  6.96,  null),
('Gazin Mullkompressen 12-fach 7,5×7,5cm unsteril', 'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'18504',        'P/100',     1,  false, 11.50,  null),
('Gazin Kompressen steril 7,5×7,5cm',               'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'L2 34260',     'P/25×2',    2,  false,  8.60,  'Mittel, steril'),
('Gazin Mullkompressen 8-fach 5×5cm steril',        'Verbandsmaterial',   (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'13620',        'P/50×2',    2,  false, 14.50,  null),
('Vacutainer Safety-Lok Blutentnahme-Set 21G',      'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'367286',       'P/50',      1,  false, 28.98,  '30cm, steril, grün, Luer'),
('Aquasonic Ultraschallgel 5L Cubitainer',          'Ultraschall / EKG',  (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'01-50',        'Stück',     1,  false, 25.10,  null),
('Aquasonic Ultraschallgel 250ml',                  'Ultraschall / EKG',  (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'01-08',        'Flasche',   3,  false,  3.70,  null),
('Signa Kontakt-Spray für Elektroden 250ml',        'Ultraschall / EKG',  (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'18-25',        'Stück',     1,  false,  4.80,  null),
('Fibral Tips grau 4,0mm',                          'Ultraschall / EKG',  (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'01.71222.002', 'P/100',     1,  false,  0.00,  'Naturalrabatt bei Bestellung'),
('Fibral Tips grau 2,5mm',                          'Ultraschall / EKG',  (SELECT id FROM lieferanten WHERE name='Ärztebedarf Scherer GmbH'),'01.71212.002', 'P/100',     1,  false,  0.00,  'Naturalrabatt bei Bestellung'),

-- Hofsteig-Apotheke
('Ostenil Plus 40mg/2ml',                           'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'Stück',     2,  true,  71.73,  'Hyaluronsäure-Injektion | 10% Rabatt'),
('Glukose 20% Miniplus 20×10ml',                    'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'Stück',     1,  false, 10.55,  '10% Rabatt'),
('WEPA Inhal NaCl Lösung 5ml',                      'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/20',      2,  false,  7.50,  '10% Rabatt'),
('Xyloneural Amp 5ml',                              'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/50',      1,  true,  40.13,  'Lokalanästhetikum | 10% Rabatt'),
('Elo-Mel Isoton Infusionslösung 500ml',            'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/10',      1,  false, 50.97,  '10% Rabatt'),
('Traumeel Amp',                                    'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/10',      1,  false, 27.82,  '10% Rabatt'),
('Volon A 10mg/1ml Amp',                            'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/5',       2,  true,  11.25,  'Kortikosteroid | 10% Rabatt'),
('Volon A 40mg/1ml Amp',                            'Medikamente',        (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'P/5',       2,  true,  29.41,  'Kortikosteroid | 10% Rabatt'),
('Infbest MPO Luer Lock',                           'Kanülen / Spritzen', (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       '9045',         'Stück',     2,  false,  0.79,  null),
('Octenisept Lösung 500ml',                         'Desinfektion',       (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'Flasche',   5,  false, 14.27,  '10% Rabatt'),
('Octenisept Lösung 1000ml',                        'Desinfektion',       (SELECT id FROM lieferanten WHERE name='Hofsteig-Apotheke'),       null,           'Flasche',   3,  false, 26.30,  '10% Rabatt');

-- 3. CHARGEN
-- (artikel_id wird per Subquery aufgelöst)

INSERT INTO chargen (artikel_id, charge_nr, menge, verfallsdatum) VALUES
((SELECT id FROM artikel WHERE bezeichnung='Dr. No Venenstauer, grün'),                          null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Nitril 3000 Handschuhe Gr. S'),                      '50030300225', 3,  '2030-01-30'),
((SELECT id FROM artikel WHERE bezeichnung='Nitril 3000 Handschuhe Gr. M'),                      '50012543',    8,  '2030-05-31'),
((SELECT id FROM artikel WHERE bezeichnung='Nitril 3000 Handschuhe Gr. L'),                      '50008484',    3,  '2030-03-31'),
((SELECT id FROM artikel WHERE bezeichnung='Vasco OP Sensitive Latexhandschuhe Gr. 7,5'),        '25M1300',     2,  '2028-12-31'),
((SELECT id FROM artikel WHERE bezeichnung='Venofix Safety G19 creme 1,10×19mm'),                '23A17',       1,  '2027-12-31'),
((SELECT id FROM artikel WHERE bezeichnung='Sterican Einmalkanülen Neuraltherapie G23 0,60×80mm'),'25F11G8852', 1,  '2030-06-01'),
((SELECT id FROM artikel WHERE bezeichnung='Omnifix Solo 3ml Einmalspritze Luer-Lock'),          '25L20C8',     1,  '2030-10-01'),
((SELECT id FROM artikel WHERE bezeichnung='Omnifix Solo 5ml Einmalspritze Luer-Lock'),          '25C24C8',     1,  '2030-03-01'),
((SELECT id FROM artikel WHERE bezeichnung='Omnifix Solo 10ml Einmalspritze Luer-Lock'),         '26A19C8',     1,  '2031-01-01'),
((SELECT id FROM artikel WHERE bezeichnung='Spritze 20ml Luer-Lock zentrisch'),                  '250526B',     1,  '2030-04-30'),
((SELECT id FROM artikel WHERE bezeichnung='DART intranasaler Zerstäuber mit 3ml Spritze'),      '250312',      1,  '2028-03-12'),
((SELECT id FROM artikel WHERE bezeichnung='Peha-haft latexfrei Fixierbinde 8cm×21m'),           '500649174',   3,  '2028-12-01'),
-- Gazofix 6cm: 2 Chargen (unterschiedliche Verfallsdaten!)
((SELECT id FROM artikel WHERE bezeichnung='Gazofix color Fixierbinde 6cm×20m grün'),            '344136',      1,  '2026-11-09'),
((SELECT id FROM artikel WHERE bezeichnung='Gazofix color Fixierbinde 6cm×20m grün'),            '536223',      2,  '2028-09-25'),
((SELECT id FROM artikel WHERE bezeichnung='Gazofix color Fixierbinde 8cm×20m grün'),            '529826',      3,  '2028-08-27'),
((SELECT id FROM artikel WHERE bezeichnung='Hansaplast Fixierpflaster Sensitive 5m×2,5cm'),      '50819282',    2,  '2028-01-30'),
((SELECT id FROM artikel WHERE bezeichnung='Schnell-Desinfektionstücher alkoholfrei Spenderdose'),'285017',     4,  '2027-06-30'),
((SELECT id FROM artikel WHERE bezeichnung='Schnell-Desinfektionstücher alkoholfrei Nachfüllpackung'),'309643', 2,  '2029-02-28'),
((SELECT id FROM artikel WHERE bezeichnung='Bode X-Wipes Spendereimer leer (Deckel grün)'),      null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Bode X-Wipes Vliesrolle 90 Tücher'),                 null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Pur-Zellin Spenderbox für Tupfer'),                  null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Pur-Zellin Zellstofftupfer keimreduziert 4×5cm'),    '593802005',   2,  '2030-11-01'),
((SELECT id FROM artikel WHERE bezeichnung='Entsorgungsbehälter Multi-Safe twin plus 3000ml'),   null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Einmalhandtücher grün 25×23cm Recycling V-Falz'),    null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='OP-Mundschutz blau 3-lagig Gummiband'),              null,        200,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Discardit II Spritze Luer zentrisch 2ml'),        null,        100,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Discardit II Spritze Luer exzentr. 5ml'),         null,        200,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Discardit II Spritze Luer exzentr. 10ml'),        null,        200,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Discardit II Spritze Luer exzentr. 20ml'),        null,        240,  null),
((SELECT id FROM artikel WHERE bezeichnung='B.Braun Sterican Insulinkanüle 30G 0,30×12mm gelb'), null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='B.Braun Sterican Kanüle 27G 0,40×40mm grau'),        null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Neopoint Sonderkanüle Tuberkulin lang 25G 0,50×40mm'),null,         2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Neopoint Einmalkanüle 23G 0,60×30mm blau'),          null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='B.Braun Sterican Kanüle 23G 0,60×60mm blau'),        null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Microlance Normkanüle 21G 0,80×40mm grün'),       null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Neopoint Einmalkanüle 20G 0,90×40mm gelb'),          null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='B.Braun Sterican Einmalkanüle 21G 0,80×80mm grün'),  null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='BD Blunt Fill Safety Aufziehkanüle 18G 1,2×40mm rot'),null,         1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Leukoplast Soft White Injektionspflaster 1,9×4cm'),  null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Leukoplast Soft White 6cm×5m'),                      null,          3,  null),
((SELECT id FROM artikel WHERE bezeichnung='Gazin Mullkompressen 12-fach 5×5cm unsteril'),       null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Gazin Mullkompressen 12-fach 7,5×7,5cm unsteril'),   null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Gazin Kompressen steril 7,5×7,5cm'),                 null,          8,  null),
((SELECT id FROM artikel WHERE bezeichnung='Gazin Mullkompressen 8-fach 5×5cm steril'),          null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Vacutainer Safety-Lok Blutentnahme-Set 21G'),        null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Aquasonic Ultraschallgel 5L Cubitainer'),            null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='Aquasonic Ultraschallgel 250ml'),                    null,         12,  null),
((SELECT id FROM artikel WHERE bezeichnung='Signa Kontakt-Spray für Elektroden 250ml'),          null,          3,  null),
((SELECT id FROM artikel WHERE bezeichnung='Fibral Tips grau 4,0mm'),                            null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Fibral Tips grau 2,5mm'),                            null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Ostenil Plus 40mg/2ml'),                             null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Glukose 20% Miniplus 20×10ml'),                      null,          2,  null),
((SELECT id FROM artikel WHERE bezeichnung='WEPA Inhal NaCl Lösung 5ml'),                        null,          7,  null),
((SELECT id FROM artikel WHERE bezeichnung='Xyloneural Amp 5ml'),                                null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Elo-Mel Isoton Infusionslösung 500ml'),              null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Traumeel Amp'),                                      null,          1,  null),
((SELECT id FROM artikel WHERE bezeichnung='Volon A 10mg/1ml Amp'),                              null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Volon A 40mg/1ml Amp'),                              null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Infbest MPO Luer Lock'),                             null,          4,  null),
((SELECT id FROM artikel WHERE bezeichnung='Octenisept Lösung 500ml'),                           null,         30,  null),
((SELECT id FROM artikel WHERE bezeichnung='Octenisept Lösung 1000ml'),                          null,         20,  null);
